# Generated by Django 3.2.19 on 2025-01-06 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Chef_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chef_App.chef')),
            ],
        ),
    ]
